homework08/src/api/urls.py
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework.routers import DefaultRouter

from .views import NoteViewSet

app_name = 'api'

router = DefaultRouter(trailing_slash=False)
router.register('notes', NoteViewSet)

urlpatterns = [
    path('jwt-auth/', obtain_jwt_token),
    path('', include(router.urls)),
]

homework08/src/notes/urls.py
from django.urls import path

from .views import (
    NoteList, NoteDetail, NoteCreate, NoteUpdate, NoteDelete
)

app_name = 'notes'

urlpatterns = [
    path('', NoteList.as_view(), name='index'),
    path('<int:pk>/', NoteDetail.as_view(), name='detail'),
    path('new/', NoteCreate.as_view(), name='create'),
    path('<int:pk>/edit/', NoteUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', NoteDelete.as_view(), name='delete'),
]

homework08/src/notes/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

from django.contrib.auth import get_user_model
import html2text

User = get_user_model()
html_t = html2text.HTML2Text()

class Note(models.Model):
    owner = models.ForeignKey(User, related_name='notes', on_delete=models.CASCADE,blank=True, null=True)
    title = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    tags = models.CharField(max_length=200)
    
    def was_published_recently(self):
        now = timezone.now()
        return now - timezone.timedelta(days=1) <= self.pub_date <= now
    
    def __str__(self):
        return self.title
    
    def tags_list(self):
        return self.tags.split(',')
  
    def content(self):
        return "\t".join([self.title, html_t.handle(self.body)])

homework08/src/notes/forms.py
from django import forms
from .models import Note

class NoteForm(forms.ModelForm):
    
    class Meta:
        model = Note
        fields = ['title', 'tags', 'body']

homework08/src/notes/views.py
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.urls import reverse, reverse_lazy

from .models import Note
from .forms import NoteForm
from .mixins import NoteMixin


class NoteList(LoginRequiredMixin, ListView):
    paginate_by = 5
    template_name = 'notes/index.html'
    context_object_name = 'latest_note_list'
    '''@method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NoteDetail, self).dispatch(*args, **kwargs)'''
    
    
    def get_queryset(self):
        return Note.objects.filter(
            owner=self.request.user,
            tags__contains=self.request.GET.get('filter_tag', ''),
            title__contains=self.request.GET.get('filter_name', '')
        ).order_by('-pub_date')


class NoteDetail(LoginRequiredMixin, DetailView):
    model = Note
    template_name = 'notes/detail.html'
    context_object_name = 'note'
    
    '''@method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(NoteDetail, self).dispatch(*args, **kwargs)'''
    

    def get_queryset(self):
        return Note.objects.filter(owner=self.request.user)


class NoteCreate(LoginRequiredMixin, NoteMixin, CreateView):
    form_class = NoteForm
    template_name = 'notes/form.html'
    success_url = reverse_lazy('notes:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.pub_date = timezone.now()
        
        return super(NoteCreate, self).form_valid(form)


class NoteUpdate(LoginRequiredMixin, NoteMixin, UpdateView):
    model = Note
    form_class = NoteForm
    template_name = 'notes/form.html'

    def get_queryset(self):
        return Note.objects.filter(
            owner=self.request.user)

    def get_success_url(self):
        return reverse('notes:update', kwargs={
            'pk': self.object.pk
        })


class NoteDelete(LoginRequiredMixin, DeleteView):
    model = Note
    success_url = reverse_lazy('notes:create')

    def get_queryset(self):
        return Note.objects.filter(owner=self.request.user)
    

homework08/src/templates/notes/detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ note.title }}</h1>

<p>{{ note.body }}</p>




{% endblock %}

homework08/src/templates/notes/form.html
{% extends "base.html" %}

{% block extra_head %}
{% load wysiwyg %}
{% wysiwyg_setup %}
{% endblock %}

{% block content %}

    <div class="row">

        <div class="col-4">
            <nav id="sidebar">

              <div class="new-note">
                <a href="{% url 'notes:create' %}" class="new-note btn btn-outline-dark">+ New Note</a>
              </div>

              <ul id="notes">
              {% if notes %}
                  {% for note in notes %}
                    <li data-url="{% url 'notes:update' note.pk %}" style='position: relative; {% if note.pk == object.pk%}border-left: 4px solid #2db9be{% endif %}'>
                        <div class="note-title btn" style="background-color: #b5e6e5;">{{ note.title }}</div>
                         {% for tag in note.tags_list %}
                              {% if tag %}
                                <div href="{% url 'notes:index' %}?filter_tag={{tag}}"  class="badge" style="background-color: #bccfcf;" style='margin: 0px 0px 0px 0px'>{{tag|lower}}</div>
                              {% endif %}
                            {% endfor %}
                        
                    </li>

                  {% endfor %}
                {% else %}
                  <li>No notes are available.</li>
              {% endif %}
                  
                  
              </ul>
            </nav>
        </div>

        <div class="col-8">

        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        {% if object %}
        <form action="{% url 'notes:update' object.pk %}" method="post" accept-charset="utf-8">
        
        {% else %}
        <form action="{% url 'notes:create' %}" method="post" accept-charset="utf-8">
        {% endif %}

            {% csrf_token %}
            {% for field in form %}
            <p>
                {% if field.errors %}
            	<div class="alert alert-danger" role="alert">
                    {{ field.errors }}
            	</div>
                {% endif %}
                {{ field }}
            </p>
            {% endfor %}
            <input type="hidden" name="next" value="{{ next }}" />

        {% if object %}
            <input class="btn btn-outline-dark" type="submit" value="Update Note"/>
            <div class="note-delete" style='position: absolute; right: 10px; top: 10px;'>
                      {% if note %}
                        <form action="{% url 'notes:delete' note.pk %}" method="post" >
                          {% csrf_token %}
                          <button class="btn btn-dark"><i class="fa fa-trash" aria-hidden="true"></i></button>
                        </form>
                      {% endif %}
                    </div>
            
        {% else %}
            <input class="btn btn-outline-dark" type="submit" value="Create Note"/>
        {% endif %}
        
        </form>

        </div>
    </div>

<script type="text/javascript">
    <a>
      $("#id_tags").tagsinput(

      );
    <a/>
    </script>

{% wysiwyg_editor "id_body" %}

{% endblock %}

homework08/src/templates/notes/index.html
{% extends "base.html" %}

{% block content %}


{% if request.GET.msg %}
<div class="row">
  <div class="alert alert-primary" role="alert">
    {{ request.GET.msg }}
  </div>
</div>
{% endif %}
<div class="row">
  <div class="col-md-5">
    {% if request.GET.filter_tag %}
      <h3>Searched:
          <a class="badge" style="background-color: #bccfcf;">{{request.GET.filter_tag}}
              </a>
      </h3>
    {% elif request.GET.filter_name %}
      <h3>Searched:
          <a style="font-size: 13pt">{{request.GET.filter_name}}
          </a></h3>
    {% endif %}

  </div>
  <div class="col">
    <form action="{% url 'notes:index' %}"class="form-inline" method="GET">
      <input name="filter_name" class="form-control" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-info" type="submit">Search</button>
    </form>
  </div>
</div>

{% if latest_note_list %}
    <ul id="notes">
    {% for note in latest_note_list %}

      <li  style="position: relative">
        <p class="row" style='margin: 10px 10px 10px 10px'>
        		<a class="btn" style="background-color: #b5e6e5;"  href="{% url 'notes:update' note.pk %}">{{ note.title }}</a>
            
                <a class="btn" style=" background-color: #e9f3f5; margin: 3px 10px 3px 10px" href="https://twitter.com//intent/tweet?text={{note.content}}{{request.META.HTTP_HOST}}{% url 'notes:detail' note.pk %}"><i class="fa fa-twitter" style="color: #2dabbe; margin: 1px 1px 1px 1px"></i></a>            
                <a class="btn" style=" background-color: #e9f3f5; margin: 3px 3px 3px 3px" href=" https://vk.com/share.php?text={{note.content}}{{request.META.HTTP_HOST}}{% url 'notes:detail' note.pk %}"><i class="fa fa-vk fa-lg vk" style="color: #2dabbe; margin: 1px 1px 1px 1px"></i></a>

            
 
            <br/>
        		
        </p>

        {% for tag in note.tags_list %}
          {% if tag %}
            <a href="{% url 'notes:index' %}?filter_tag={{tag}}"  class="badge" style="background-color: #bccfcf;" style='margin: 0px 0px 0px 0px'>{{tag|lower}}</a>
          {% endif %}
        {% endfor %}



        </li>
        
    {% endfor %}
    </ul>
{% else %}
    <p>No notes are available.</p>
{% endif %}

{% if is_paginated %}
<div class="pagination">
   <span class="step-links">
       {% if page_obj.has_previous %}
           <a href="?page={{ page_obj.previous_page_number }}&filter_tag={{request.GET.filter_tag}}&filter_name={{request.GET.filter_name}}"><button type="button" class="btn btn-outline-info" style='margin: 4px 4px 4px 4px'><i class="fa fa-backward" >
              </i></button>
              </a>
       {% endif %}

       <span class="current">
           Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
       </span>

       {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}&filter_tag={{request.GET.filter_tag}}&filter_name={{request.GET.filter_name}}" >
              <button type="button" class="btn btn-outline-info" style='margin: 4px 4px 4px 4px'><i class="fa fa-forward" >
              </i></button></a>
       {% endif %}
  </span>
</div>
{% endif %}

<a class="btn btn-outline-dark" style="background-color: #077a7a;" href="{% url 'notes:create' %}">Create a new note</a>

{% endblock %}